-- 1. List the number of films per category.

SELECT fc.category_id, c.name AS name, 
COUNT(f.title) AS title FROM sakila.film_category AS fc
JOIN sakila.film AS f
ON fc.film_id = f.film_id
JOIN sakila.category AS c
ON c.category_id = fc.category_id
GROUP BY c.category_id, name
ORDER BY name;

-- 2. Retrieve the store ID, city, and country for each store.

-- store,city and country, address

SELECT s.store_id, a.address, c.city, co.country FROM sakila.store AS s
JOIN sakila.address AS a
ON s.address_id = a.address_id
JOIN sakila.city AS c
ON a.city_id = c.city_id
JOIN sakila.country as co
ON c.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, SUM(p.amount) AS Total_revenue FROM sakila.store AS s
JOIN sakila.customer AS c
ON s.store_id = c.store_id
JOIN sakila.payment AS p
ON c.customer_id = p.customer_id
GROUP BY store_id;

-- 4. Determine the average running time of films for each category.


SELECT c.name, ROUND(AVG(f.length),2) AS Average_time FROM sakila.film AS f
JOIN sakila.film_category AS fc
ON f.film_id = fc.film_id
JOIN sakila.category AS c
ON fc.category_id = c.category_id
GROUP BY c.name;
